---
- name: Print versions of various tools to a file
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get CLI tools versions
      command: "{{ item }}"
      loop:
        - ansible --version
        - git --version
        - curl --version
      register: cli_tools_output

    - name: Get Build tools versions
      command: "{{ item }}"
      loop:
        - python3 --version
        - make --version
        - gcc --version
      register: build_tools_output

    - name: Create version report file
      copy:
        dest: /tmp/tools_version_report.txt
        content: ""
        force: yes

    - name: Append CLI tools versions to file
      blockinfile:
        path: /tmp/tools_version_report.txt
        marker: ""
        block: |
          CLI Tools:
          {% for item in cli_tools_output.results %}
          - {{ item.stdout.split('\n')[0] }}
          {% endfor %}

    - name: Append Build tools versions to file
      blockinfile:
        path: /tmp/tools_version_report.txt
        marker: ""
        block: |
          Build Tools:
          {% for item in build_tools_output.results %}
          - {{ item.stdout.split('\n')[0] }}
          {% endfor %}
