---
- name: Print versions of tools and write to a file in a nicely formatted structure
  hosts: localhost
  gather_facts: no
  vars:
    tool_groups:
      cli:
        - ansible --version
        - git --version
        - curl --version
      build:
        - python3 --version
        - make --version
        - gcc --version
  tasks:
    - name: Create version report file
      copy:
        dest: /tmp/tools_version_report.txt
        content: ""
        force: yes

    - name: Get tool versions
      command: "{{ item }}"
      loop: "{{ tool_groups.cli + tool_groups.build }}"
      register: tool_versions

    - name: Organize CLI and Build tool versions
      set_fact:
        cli_tool_versions: "{{ tool_versions.results[:tool_groups.cli | length] }}"
        build_tool_versions: "{{ tool_versions.results[tool_groups.cli | length:] }}"

    - name: Format and append CLI tools versions to file
      blockinfile:
        path: /tmp/tools_version_report.txt
        marker: ""
        block: |
          CLI Tools:
          {% for tool in cli_tool_versions %}
          - {{ tool.item.split()[0] }}: {{ tool.stdout.split('\n')[0] }}
          {% endfor %}

    - name: Format and append Build tools versions to file
      blockinfile:
        path: /tmp/tools_version_report.txt
        marker: ""
        block: |
          Build Tools:
          {% for tool in build_tool_versions %}
          - {{ tool.item.split()[0] }}: {{ tool.stdout.split('\n')[0] }}
          {% endfor %}
