---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    tool_name: "Ansible CLI"
    tool_command: "ansible --version | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\\1/p'"

  tasks:
    # Initialize a dictionary to store the result
    - name: Initialize version tracking
      set_fact:
        version_results: {}

    # Collect the tool version
    - name: Collect tool version
      shell: "{{ tool_command }}"
      register: tool_version_output
      failed_when: false
      changed_when: false

    # Set the collected version into the results dictionary
    - name: Set version result for the tool
      set_fact:
        version_results:
          "{{ version_results | default({}) | combine({tool_name: {'name': tool_name, 'version': tool_version_output.stdout}}) }}"
      when:
        - tool_version_output.stdout is defined

    # Display the collected tool version in a formatted way
    - name: Display Tool Version
      debug:
        msg: |
          ========== TOOL VERSION ==========
          Tool Name       : {{ version_results[tool_name].name }}
          Tool Version    : {{ version_results[tool_name].version }}
          ============================
