name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger for tags like v1.0.0

jobs:
   create-release:
    runs-on: self-hosted

    steps:
    - name: Generate Release Notes
      id: notes
      run: |
        echo "## Release Notes" > release_notes.md
        echo "- Image 1: myrepo/image1:${GITHUB_REF_NAME}" >> release_notes.md
        echo "- Image 2: myrepo/image2:${GITHUB_REF_NAME}" >> release_notes.md
        echo "- Image 3: myrepo/image3:${GITHUB_REF_NAME}" >> release_notes.md
        echo "" >> release_notes.md
        if [ -f release_notes_input.md ]; then
          echo "Appending content from release_notes_input.md"
          cat release_notes_input.md >> release_notes.md
        else
          echo "No additional release notes found."
        fi
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body_path: release_notes.md
        draft: false
        prerelease: false
