name: Generate Pie Chart in Summary

on: 
  workflow_dispatch:

jobs:
  generate_chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Generate Pie Chart
        run: |
          echo "
          import matplotlib.pyplot as plt
          
          # Example data for pie chart
          labels = ['Success', 'Failure', 'Skipped']
          sizes = [70, 20, 10]  # Replace with actual data
          colors = ['#4CAF50', '#FF5733', '#FFC300']
          
          plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%')
          plt.title('GitHub Actions Workflow Summary')
          plt.savefig('/tmp/summary_chart.png')
          " > chart.py
          python chart.py

      - name: Convert Image to Base64 and Display in Summary
        run: |
          # Convert the image to base64
          base64_img=$(base64 /tmp/summary_chart.png)
          # Display it in the job summary
          echo "![Pie Chart](data:image/png;base64,$base64_img)" >> $GITHUB_STEP_SUMMARY
